spring:
  profiles: dev


  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/test1
    username: sa
    password: 
  h2:
      console:
        enabled: true
        path: /h2-console
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
server:
  port: 8080
  
  
logging:
   level:
     org:
      springframework: INFO
   

  
---
    
spring:
   profiles: QA

   datasource:
     driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
     url: jdbc:sqlserver://mspw-ddedb-deprod01.database.windows.net:1433;DatabaseName=DDEDB-DEPROD01
     username:
     password:

   jpa:
     hibernate.ddl-auto: none
     generate-ddl: false
     show-sql: true
     properties:
       hibernate:
         dialect: org.hibernate.dialect.SQLServerDialect
         default_schema: ods
   server:
     port: 8080


  
